export const TASK_LIST_REQUEST = 'TASK_FILE_LOAD'
export const TASK_LIST_SUCCESS = 'TASK_FILE_SUCCESS'
export const TASK_LIST_FAIL = 'TASK_FILE_FAIL'
export const TASK_LIST_RESET = 'TASK_FILE_RESET'

export const TASK_CREATE_REQUEST = 'TASK_CREATE_LOAD'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL'

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_LOAD'
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS'
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL'

export const TASK_DELETE_REQUEST = 'TASK_DELETE_LOAD'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL'